Added a link on QPT landing page
magento/knowledge-base pull request #102
Opened 2021-11-04 19:40 UTC by viktym

## Purpose of this pull request
 
Add a link on QPT landing page
 
## Affected Support KB pages
 

 
https://support.magento.com/hc/en-us/articles/360047139492-Magento-Quality-Patches-released-new-tool-to-self-serve-quality-patches

2021-11-17 16:52 UTC, almarchenko commented
@Rinn22  please don't import yet

2021-11-22 20:59 UTC, almarchenko requested changes

2021-11-22 20:59 UTC, almarchenko commented on src/announcements/adobe-commerce-announcements/magento-quality-patches-released-new-tool-to-self-serve-quality-patches.md
> +* [Available patches in Quality Patches Tool](https://devdocs.magento.com/quality-patches/tool.html#patch-grid)
```suggestion
* [Patches available in Quality Patches Tool](https://devdocs.magento.com/quality-patches/tool.html#patch-grid)
```
```suggestion
* [Available patches in Quality Patches Tool](https://devdocs.magento.com/quality-patches/tool.html#patch-grid)
```

2021-11-22 21:00 UTC, almarchenko requested changes

2021-11-22 21:00 UTC, almarchenko commented on src/announcements/adobe-commerce-announcements/magento-quality-patches-released-new-tool-to-self-serve-quality-patches.md
> +* [Available patches in Quality Patches Tool](https://devdocs.magento.com/quality-patches/tool.html#patch-grid)
```suggestion
* [Patches available in Quality Patches Tool](https://devdocs.magento.com/quality-patches/tool.html#patch-grid)
```

2021-11-22 21:12 UTC, almarchenko approved these changes

2021-11-22 21:12 UTC, almarchenko commented
@magento import code to magento-kb/knowledge-base

2021-11-22 21:12 UTC, m2-github-services commented
@almarchenko the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-viktym-knowledge-base-102`.

2021-11-22 21:24 UTC, merged