Update elasticsuite-tracking-indices-causes-problems-with-elasticsear…
magento/knowledge-base pull request #140
Opened 2022-05-16 15:26 UTC by romainruaud

…ch.md

## Purpose of this pull request
 
This pull request (PR) ...
 
## Affected Support KB pages
 

 
List the affected pages on support.magento.com (URLs).

2022-05-19 10:28 UTC, BarnyShergold requested changes
Please also sign the Adobe CLA to allow the PR to progress once passed

2022-05-19 10:28 UTC, BarnyShergold commented on src/troubleshooting/general/elasticsuite-tracking-indices-causes-problems-with-elasticsearch.md
> +### Upgrade your Elasticsuite version to be able to cleanup tracking indices periodically
```suggestion
### Upgrade your ElasticSuite version to be able to cleanup tracking indices periodically
```

2022-05-19 10:28 UTC, BarnyShergold commented on src/troubleshooting/general/elasticsuite-tracking-indices-causes-problems-with-elasticsearch.md
> +### Upgrade your Elasticsuite version to use monthly based indices instead of daily based indices
```suggestion
### Upgrade your ElasticSuite version to use monthly based indices instead of daily based indices
```

2022-05-19 12:27 UTC, BarnyShergold approved these changes
Thanks for the super quick turn around.

2022-05-25 15:29 UTC, tanay-sharma commented on src/troubleshooting/general/elasticsuite-tracking-indices-causes-problems-with-elasticsearch.md
> +### Upgrade your ElasticSuite version to be able to cleanup tracking indices periodically
```suggestion
### Upgrade your ElasticSuite version to be able to clean up tracking indices periodically
```

2022-05-25 16:00 UTC, almarchenko commented
I will close this one, cause it is replaced by #142

2022-05-25 16:00 UTC, closed without merging