Update elasticsuite-tracking-indices-causes-problems-with-elasticsear…
magento/knowledge-base pull request #142
Opened 2022-05-24 10:08 UTC by romainruaud

…ch.md

## Purpose of this pull request
 
Replace PR #140 because target page has moved.
 
## Affected Support KB pages
 

 
https://support.magento.com/hc/en-us/articles/360034921492

2022-05-24 17:16 UTC, almarchenko commented
@romainruaud  thank you! I'm sorry that we moved it before merging your PR, will process this

2022-05-31 20:13 UTC, almarchenko commented
Requested review from Adobe Commerce SMEs.

2022-06-03 20:38 UTC, almarchenko requested changes
Please commit the suggested changes and I would be able to import and merge.
Thank you

2022-06-03 20:38 UTC, almarchenko commented on src/troubleshooting/elasticsearch/elasticsuite-tracking-indices-causes-problems-with-elasticsearch.md
> +Go to **Stores > Configuration > Tracking > Global Configuration > Retention Delay**
```suggestion
Go to **Stores** > **Configuration** > **Tracking** > **Global Configuration** > **Retention Delay**
```

2022-06-03 20:38 UTC, almarchenko commented on src/troubleshooting/elasticsearch/elasticsuite-tracking-indices-causes-problems-with-elasticsearch.md
> +Go to **Stores > Configuration > Tracking > Global Configuration > Retention Delay**
```suggestion
Go to **Stores** > **Configuration** > **Tracking** > **Global Configuration** > **Retention Delay**
```

2022-06-09 08:12 UTC, romainruaud commented
Hi, I updated the requests

2022-06-21 19:11 UTC, almarchenko commented
@magento import code to magento-kb/knowledge-base

2022-06-23 14:55 UTC, merged