Create wiki
magento/knowledge-base pull request #46
Opened 2021-06-17 11:49 UTC by manavluhar

Adding wiki for  **Adobe Commerce Support Knowledge Base**

## Purpose of this pull request
 
This pull request (PR) ...
 
## Affected Support KB pages
 

 
List the affected pages on support.magento.com (URLs).

2021-06-21 21:37 UTC, BarnyShergold requested changes

2021-06-21 21:37 UTC, BarnyShergold commented on wiki
> +This repository contains the markdown source of articles, published in Adobe Commerce Support Knowledge Base.
```suggestion
This repository contains the markdown source of articles, published in the Adobe Commerce Support Knowledge Base.
```

2021-06-21 21:37 UTC, BarnyShergold commented on wiki
> +Getting started with our contribution program is easy. You can start with a simple page edit, and then work your way up to major revisions and new topics. The more participation we have from the Mage
```suggestion
Getting started with our contribution program is easy. You can start with a simple page edit, then work your way up to major revisions and new topics. The more participation we have from the Magento community, the better the docs are for everyone!
```

2021-06-22 12:47 UTC, manavluhar commented
Thank you @BarnyShergold I accepted suggestions.

2021-06-22 22:19 UTC, almarchenko commented
@magento import code to magento-kb/knowledge-base

2021-06-22 22:20 UTC, magento-engcom-team commented
@almarchenko the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-46`.

2021-06-23 21:04 UTC, almarchenko approved these changes

2021-06-24 13:25 UTC, BarnyShergold approved these changes

2021-06-25 14:10 UTC, almarchenko commented
@manavluhar  I'm not sure publishing a wiki page is possible using our existing process, but I will try! If it doesn't get through, we'll add manually and add points manually. (unless I find some better solution)

2021-06-25 14:11 UTC, almarchenko commented
@magento import code to magento-kb/knowledge-base

2021-06-25 14:12 UTC, magento-engcom-team commented
@almarchenko the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-46`.

2021-06-25 14:30 UTC, merged