Corrected Title
magento/knowledge-base pull request #71
Opened 2021-08-11 16:29 UTC by BarnyShergold

## Purpose of this pull request
 
This pull request (PR) fixes issue #69 
 
## Affected Support KB pages
 
https://support.magento.com/hc/en-us/articles/360049045351

2021-08-18 17:33 UTC, almarchenko requested changes

2021-08-18 17:33 UTC, almarchenko commented on src/best-practices/general/magento-commerce-cloud-best-practice-for-slave-connection.md
> +title: Adobe Commerce on cloud architecture best practice for MySQL slave connection
```suggestion
title: Adobe Commerce on our cloud infrastructure best practice for MySQL slave connection
```

2021-08-18 17:33 UTC, almarchenko commented on src/best-practices/general/magento-commerce-cloud-best-practice-for-slave-connection.md
> +title: Adobe Commerce on cloud architecture best practice for MySQL slave connection
I know we used architecture ourselves, but there was a twist and it will be "on our cloud infrastructure" (and "our" is required).

2021-08-20 18:39 UTC, almarchenko approved these changes

2021-08-20 18:43 UTC, almarchenko commented
@magento import code to magento-kb/knowledge-base

2021-08-20 18:44 UTC, magento-engcom-team commented
@almarchenko the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-71`.

2021-08-20 19:00 UTC, merged