Replace Magento with Adobe Commerce
magento/knowledge-base pull request #79
Opened 2021-08-27 16:12 UTC by BarnyShergold

## Purpose of this pull request
 
This pull request (PR) fixes issue #57 & #56
 
## Affected Support KB pages
 
https://support.magento.com/hc/en-us/articles/360049171211-Best-practices-for-render-blocking-resources-in-Magento-
https://support.magento.com/hc/en-us/articles/4402349423757-Error-purging-cache-in-Magento-Commerce-Admin

Query - The products are now known as Adobe Commerce & Adobe Commerce Cloud - using just commerce and then referring to "our cloud infrastructure" might be confusing and it a little long winded?

2021-08-30 21:19 UTC, almarchenko requested changes

2021-08-30 21:19 UTC, almarchenko commented on src/best-practices/general/best-practices-for-render-blocking-resources-in-magento.md
> +* Adobe Commerce Cloud, all [supported versions](https://magento.com/sites/default/files/magento-software-lifecycle-policy.pdf)
```suggestion
* Adobe Commerce on our cloud infrastructure, all [supported versions](https://magento.com/sites/default/files/magento-software-lifecycle-policy.pdf) 
```

2021-08-30 21:19 UTC, almarchenko commented on src/best-practices/general/best-practices-for-render-blocking-resources-in-magento.md
> +* KB [Optimize CSS and JS files Adobe Commerce Cloud and Adobe Commerce](https://support.magento.com/hc/en-us/articles/360044482152-CSS-and-Javascript-file-optimization-on-Magento-Commerce-Cloud-and-
```suggestion
* KB [Optimize CSS and JS files Adobe Commerce](https://support.magento.com/hc/en-us/articles/360044482152-CSS-and-Javascript-file-optimization-on-Magento-Commerce-Cloud-and-Magento-Commerce) 
```

2021-08-30 21:19 UTC, almarchenko commented on src/troubleshooting/general/error-purging-cache-in-admin.md
> +Adobe Commerce and Adobe Commerce Cloud: 2.3.0-2.3.7, 2.4.0-2.4.2-p1
```suggestion
Adobe Commerce, all deployment types: 2.3.0-2.3.7, 2.4.0-2.4.2-p1
```

2021-09-07 19:35 UTC, almarchenko approved these changes

2021-09-07 19:35 UTC, almarchenko commented
@magento import code to magento-kb/knowledge-base

2021-09-07 19:36 UTC, magento-engcom-team commented
@almarchenko the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-79`.

2021-09-07 20:08 UTC, merged